# Nixpacks configuration for Coolify Installation
# Ensures necessary packages are available for running Docker and Coolify

[phases.setup]
nixPkgs = ["bash"]
aptPkgs = ["curl", "wget", "ca-certificates", "gnupg", "lsb-release", "openssh-server", "docker.io"]

[phases.install]
cmds = ["echo 'Skipping npm install - not needed for this project'"]

[phases.build]
cmds = ["echo 'No build step needed'"]

[start]
cmd = "bash install-coolify.sh && tail -f /dev/null"
